### ISSUE TITLE
TAIKO_BROWSER_ARGS fails when command-line flags include embedded commas

### ISSUE THREAD

**Issue by scottdavis99** [getgauge/taiko#1261]
### Actual behavior
Chrome command-line flags (--window-position, --window-size) set in TAIKO_BROWSER_ARGS fail/are ignored due to embedded commas.

TAIKO_BROWSER_ARGS='--window-size=1024,768', '--window-position=2048,0' taiko myscript.js

TAIKO_BROWSER_ARGS=--window-size=1024,768, --window-position=2048,0 taiko myscript.js

I am trying to achieve feature parity between what I can accomplish in code and what I can accomplish from the command-line. This script works as expected:

```
const { openBrowser, closeBrowser } = require('taiko');
(async () => {                    
    try {                       
        await openBrowser({args:['--window-size=1024,768', 
                                 '--window-position=2048,0']});
        screenshot()
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

I'm not able to pass in command-line flags, even without embedded commas, so this may be a larger problem that just the commas.

```
TAIKO_BROWSER_ARGS=--incognito taiko myscript.js
```

### Versions
```
Version: 1.0.9 (Chromium:83.0.4103.0)
```

**Comment by zabil** [comment]
Fixed via https://github.com/getgauge/taiko/pull/1252

Can you pull the latest version and check if this works?

**Comment by scottdavis99** [comment]
Unless I'm getting the syntax wrong, this still appears to be an open issue with the latest version:
Version: 1.0.10 (Chromium:84.0.4128.0)

I can confirm that this works:
TAIKO_BROWSER_ARGS=--incognito taiko --observe simple.js

Chromium does, indeed, open in incognito mode.

----

This does not work. The size of the browser window does not match the screen dimensions requested. The browser size is identical to the above "incognito" request (where the screen dimensions are left to the default size).
TAIKO_BROWSER_ARGS=--window-size=1024,768 taiko --observe simple.js

Chromium opens with two tabs, one blank and the other with the IP address of 0.0.3.0

----

This does not work, either. I would expect the Chromium window to open at a different screen location, which it does not.
TAIKO_BROWSER_ARGS=--window-position=2048,0 taiko --observe simple.js

Chromium opens with two tabs, one blank and the other with the IP address of 0.0.3.0

----

My goal is to combine these two:
TAIKO_BROWSER_ARGS=--window-size=1024,768,--window-position=2048,0 taiko --observe simple.js

**Comment by zabil** [comment]
> Can you pull the latest version (from master) and check if this works?

1.1.10 still had this problem. However, 1.1.11 (then on master) was supposed to have the fix

https://github.com/getgauge/taiko/pull/1252/files#diff-c626d926eeff4a14b1c1f5114bcc21c5R289-R293

but looks like it fixed something else. Thanks for pointing it out.

I can confirm that `TAIKO_BROWSER_ARGS=--window-position=2048,0 taiko --observe simple.js` does not work on 1.1.10

**Comment by zabil** [comment]
My bad, this is fixed in `1.0.11`. Please make sure that `package.json` and `node_module` folders use the latest version before running the scripts.
